version: "3.9"

services:
  movie:
    container_name: movie_container
    build: ./movie/
    ports:
      - "3200:3200"
  showtime:
    container_name: showtime_container
    build: ./showtime/
    ports:
      - "3202:3202"
  user:
    container_name: user_container
    build: ./user/
    ports:
        - "3203:3203"
    environment:
      - BOOKING_SERVICE_URL=http://booking_container:3201
      - MOVIE_SERVICE_URL=http://movie_container:3200
  booking:
    container_name: booking_container
    build: ./booking/
    ports:
        - "3201:3201"
    environment:
      - TIMES_SERVICE_URL=http://showtime_container:3202

